# Generated by Django 2.1.7 on 2019-03-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Item',
        ),
    ]
