# Generated by Django 2.1.7 on 2019-03-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190303_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-title',)},
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
